[project]
name = "odoo-addons-oca-l10n-thailand"
version = "18.0.20250821.0"
dependencies = [
    "odoo-addon-l10n_th_account_tax==18.0.*",
    "odoo-addon-l10n_th_account_tax_report==18.0.*",
    "odoo-addon-l10n_th_account_wht_cert_form==18.0.*",
    "odoo-addon-l10n_th_amount_to_text==18.0.*",
    "odoo-addon-l10n_th_base_sequence==18.0.*",
    "odoo-addon-l10n_th_base_utils==18.0.*",
    "odoo-addon-l10n_th_mis_report==18.0.*",
    "odoo-addon-l10n_th_partner==18.0.*",
    "odoo-addon-l10n_th_tier_department==18.0.*",
    "odoo-addon-l10n_th_tier_department_demo==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
